# Generated by Django 3.1.7 on 2021-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDetails',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('userId', models.DecimalField(decimal_places=0, max_digits=10)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JSONFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
